/*
  THis is for defining table schema / Postgres SQL
*/
CREATE TABLE companies (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  company_type  TEXT,
  website       TEXT
);

CREATE TABLE tools (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id         BIGINT REFERENCES companies(id),
  name               TEXT NOT NULL,
  tool_type          TEXT,
  cost               NUMERIC(10,2),
  integrations       TEXT,
  notes              TEXT,
  last_reviewed_date TIMESTAMPTZ,
  url                TEXT,
  created_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE research_methods (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE research_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE research_method_category_map (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES research_categories(id),
  method_id   BIGINT NOT NULL REFERENCES research_methods(id),
  UNIQUE (category_id, method_id)
);

CREATE TABLE research_obstacles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  category_id BIGINT REFERENCES research_categories(id),
  description TEXT,
  workarounds TEXT
);

CREATE TABLE tool_obstacles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id     BIGINT NOT NULL REFERENCES tools(id),
  obstacle_id BIGINT NOT NULL REFERENCES research_obstacles(id),
  notes       TEXT,
  rating      INT CHECK (rating BETWEEN 1 AND 5),
  UNIQUE (tool_id, obstacle_id)
);

CREATE TABLE tool_review (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id             BIGINT NOT NULL REFERENCES tools(id),
  research_method_id  BIGINT REFERENCES research_methods(id),
  content             TEXT,
  date_posted         TIMESTAMPTZ,
  source              TEXT,
  review_summary      TEXT,
  created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE universities (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  library_name  TEXT,
  library_url   TEXT,
  date_reviewed TIMESTAMPTZ,
  notes         TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE university_tools (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES universities(id),
  tool_id       BIGINT NOT NULL REFERENCES tools(id),
  access_type   TEXT,
  date_granted  TIMESTAMPTZ,
  notes         TEXT,
  UNIQUE (university_id, tool_id)
);

CREATE TABLE job_descriptions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id    BIGINT REFERENCES companies(id),
  title         TEXT NOT NULL,
  website       TEXT,
  posted_date   TIMESTAMPTZ,
  sector        TEXT,
  location      TEXT,
  in_person_days INT,
  salary_low    INT,
  salary_high   INT,
  other_details TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE job_post_source (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id      BIGINT NOT NULL REFERENCES job_descriptions(id),
  source_name TEXT NOT NULL,
  UNIQUE (job_id, source_name)
);

CREATE TABLE skills (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  skill_category  TEXT,
  description     TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE job_skills (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           BIGINT NOT NULL REFERENCES job_descriptions(id),
  skill_id         BIGINT NOT NULL REFERENCES skills(id),
  level_required   TEXT,
  years_experience INT,
  notes            TEXT,
  UNIQUE (job_id, skill_id)
);

CREATE TABLE job_tools (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id         BIGINT NOT NULL REFERENCES job_descriptions(id),
  tool_id        BIGINT NOT NULL REFERENCES tools(id),
  required_level TEXT,
  notes          TEXT,
  UNIQUE (job_id, tool_id)
);

CREATE TABLE job_methods (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id           BIGINT NOT NULL REFERENCES job_descriptions(id),
  method_id        BIGINT NOT NULL REFERENCES research_methods(id),
  importance       INT,
  experience_level TEXT,
  UNIQUE (job_id, method_id)
);

CREATE TABLE use_cases (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  research_method_id BIGINT REFERENCES research_methods(id),
  category_id        BIGINT REFERENCES research_categories(id),
  example            TEXT,
  note               TEXT,
  created_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tool_methods (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id   BIGINT NOT NULL REFERENCES tools(id),
  method_id BIGINT NOT NULL REFERENCES research_methods(id),
  notes     TEXT,
  required  BOOLEAN DEFAULT false,
  UNIQUE (tool_id, method_id)
);

CREATE TABLE tool_use_cases (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id          BIGINT NOT NULL REFERENCES tools(id),
  use_case_id      BIGINT NOT NULL REFERENCES use_cases(id),
  notes            TEXT,
  confidence_level TEXT,
  UNIQUE (tool_id, use_case_id)
);

-- Features
CREATE TABLE features (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT NOT NULL,
  description       TEXT,
  feature_category  TEXT,
  created_at        TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tool_feature (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id   BIGINT NOT NULL REFERENCES tools(id),
  feature_id BIGINT NOT NULL REFERENCES features(id),
  available BOOLEAN DEFAULT true,
  notes     TEXT,
  UNIQUE (tool_id, feature_id)
);

CREATE TABLE research_method_features (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  method_id BIGINT NOT NULL REFERENCES research_methods(id),
  feature_id BIGINT NOT NULL REFERENCES features(id),
  notes     TEXT,
  UNIQUE (method_id, feature_id)
);
